spring:
  application:
    name: turAl-telegram-bot
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/tural-telegram-bot
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  main:
    allow-bean-definition-overriding: true

bot:
  username: TURAL_AL_bOt
  token: 6272012662:AAEmo1Hsd5Th-r35YjBOlD7aOwUhSUtROhg
  path:  ${NGROK}

redis:
  host: ${WEB_FORM_REDIS_HOST:localhost}
  port: ${WEB_FORM_REDIS_HOST:6379}
  username: ${WEB_FORM_REDIS_HOST:}
  password: ${WEB_FORM_REDIS_HOST:}