spring:
  application:
    name: turAl-telegram-bot
  datasource:
    password: 2002148
    url: jdbc:postgresql://localhost:5432/tural-telegram-bot
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true